import type { Book, WishlistItem, LendingItem } from './types';

export const SEED_BOOKS: Book[] = [
  {
    id: '1',
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    cover: '🚀',
    status: 'reading',
    rating: 5,
    progress: 67,
    startDate: '2024-02-01',
    notes: '',
    genre: 'Sci-Fi',
    pages: 476,
  },
  {
    id: '2',
    title: 'Atomic Habits',
    author: 'James Clear',
    cover: '🔵',
    status: 'read',
    rating: 4,
    progress: 100,
    startDate: '2024-01-05',
    finishDate: '2024-01-20',
    notes: 'Great practical advice on building habits.',
    genre: 'Self-Help',
    pages: 320,
  },
  {
    id: '3',
    title: 'Dune',
    author: 'Frank Herbert',
    cover: '🏜️',
    status: 'read',
    rating: 5,
    progress: 100,
    startDate: '2023-11-10',
    finishDate: '2023-12-01',
    notes: 'A masterpiece.',
    genre: 'Sci-Fi',
    pages: 688,
  },
  {
    id: '4',
    title: 'Sapiens',
    author: 'Yuval Noah Harari',
    cover: '🌍',
    status: 'read',
    rating: 4,
    progress: 100,
    startDate: '2023-09-01',
    finishDate: '2023-10-05',
    notes: '',
    genre: 'History',
    pages: 443,
  },
  {
    id: '5',
    title: 'The Pragmatic Programmer',
    author: 'Hunt & Thomas',
    cover: '💻',
    status: 'reading',
    rating: 5,
    progress: 42,
    startDate: '2024-02-15',
    notes: '',
    genre: 'Tech',
    pages: 352,
  },
  {
    id: '6',
    title: 'Thinking, Fast and Slow',
    author: 'Daniel Kahneman',
    cover: '🧠',
    status: 'read',
    rating: 3,
    progress: 100,
    startDate: '2023-07-01',
    finishDate: '2023-08-20',
    notes: 'Dense but rewarding.',
    genre: 'Psychology',
    pages: 499,
  },
];

export const SEED_WISHLIST: WishlistItem[] = [
  {
    id: 'w1',
    title: 'The Midnight Library',
    author: 'Matt Haig',
    cover: '🌙',
    genre: 'Fiction',
    priority: 'high',
    addedDate: '2024-01-15',
  },
  {
    id: 'w2',
    title: 'Norwegian Wood',
    author: 'Haruki Murakami',
    cover: '🌲',
    genre: 'Fiction',
    priority: 'medium',
    addedDate: '2024-01-20',
  },
  {
    id: 'w3',
    title: 'The Design of Everyday Things',
    author: 'Don Norman',
    cover: '🎨',
    genre: 'Design',
    priority: 'high',
    addedDate: '2024-02-01',
  },
  {
    id: 'w4',
    title: 'Meditations',
    author: 'Marcus Aurelius',
    cover: '🏛️',
    genre: 'Philosophy',
    priority: 'low',
    addedDate: '2024-02-10',
  },
  {
    id: 'w5',
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    cover: '🎵',
    genre: 'Fantasy',
    priority: 'high',
    addedDate: '2024-02-20',
  },
];

export const SEED_LENDING: LendingItem[] = [
  {
    id: 'l1',
    bookTitle: 'Atomic Habits',
    borrower: 'Sarah',
    lentDate: '2024-03-01',
    dueDate: '2024-04-01',
    returned: false,
  },
  {
    id: 'l2',
    bookTitle: 'Sapiens',
    borrower: 'Mike',
    lentDate: '2024-02-10',
    dueDate: '2024-03-10',
    returned: false,
  },
];
